spring:
  session:
    storage-type: redis
  cache:
    type: redis
  redis:
    host: localhost
    port: 6000
#    sentinel:
#      master: mymaster
#      nodes: localhost:26379, localhost:26380, localhost:26381
